services:
  - type: web
    name: bharatshop-searxng
    runtime: docker
    plan: free
    branch: master
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: SEARXNG_SECRET
        generateValue: true
      - key: SEARXNG_PORT
        value: "10000"
      - key: SEARXNG_BIND_ADDRESS
        value: "0.0.0.0"
      - key: SEARXNG_LIMITER
        value: "false"
      - key: SEARXNG_PUBLIC_INSTANCE
        value: "false"
      - key: SEARXNG_IMAGE_PROXY
        value: "false"
