general:
  debug: false
  instance_name: "BharatShop Image Search"
  enable_metrics: false

search:
  safe_search: 1
  default_lang: "en"
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  suspended_times:
    SearxEngineTooManyRequests: 180
  formats:
    - html
    - json

server:
  port: 10000
  bind_address: "0.0.0.0"
  base_url: false
  limiter: false
  public_instance: false
  secret_key: "${SEARXNG_SECRET}"
  image_proxy: false
  method: "GET"

outgoing:
  request_timeout: 8.0
  pool_connections: 20
  pool_maxsize: 10
  enable_http2: true

ui:
  default_theme: simple

categories_as_tabs:
  images:
  general:

engines:
  - name: google images
    engine: google_images
    shortcut: gi
    categories: [images]
    paging: true
    max_page: 10
    timeout: 8.0
    disabled: false
