use_default_settings: true

general:
  debug: false
  instance_name: "BharatShop Search"

search:
  safe_search: 1
  autocomplete: "duckduckgo"
  default_lang: "en"
  formats:
    - html
    - json

server:
  limiter: false
  public_instance: false
  image_proxy: false

outgoing:
  request_timeout: 12.0
  max_request_timeout: 15.0
